"use client";

import { motion } from "framer-motion";
import { Download, FileCheck2, LockKeyhole, Mic2, ShieldCheck, Siren, TestTube2, Wifi } from "lucide-react";
import benchmark from "@/public/benchmark/audio-deepfake-subset.json";
import { complianceConfigs } from "@/lib/compliance";
import { useAegisStore } from "@/lib/store";
import { BenchmarkEvidenceCard } from "./BenchmarkEvidenceCard";
import { ImplementationBadge } from "./ImplementationBadge";

const proofRows = [
  {
    title: "Live vs simulated disclosure",
    level: "live" as const,
    evidence: "Every major surface uses Live, Heuristic, Simulated, or Seeded demo labels. The export repeats this disclosure in JSON.",
    action: "Open Proof or Audit before Q&A."
  },
  {
    title: "Guardian SOS intervention",
    level: "live" as const,
    evidence: "Trust score below 40 fires one browser ThreatEvent and Web Speech Synthesis warning, then shows Guardian action buttons.",
    action: "Click Cloned voice or CEO deepfake."
  },
  {
    title: "Groq honeypot extraction",
    level: "live" as const,
    evidence: "When NEXT_PUBLIC_GROQ_API_KEY is valid, Margaret is generated by Groq. Fallback is visibly labeled when offline.",
    action: "Run Judge Demo, then inspect Honeypot/Audit."
  },
  {
    title: "Privacy architecture",
    level: "live" as const,
    evidence: "Privacy screen states raw audio stays local, transcripts are ephemeral, and Groq receives honeypot text only.",
    action: "Open Privacy during judge Q&A."
  },
  {
    title: "Export incident report",
    level: "live" as const,
    evidence: "Export downloads a PDF report with trust score, reasons, compliance mode, honeypot provider, extracted intel, and audit events.",
    action: "Click Export in header or Audit screen."
  },
  {
    title: "Audio deepfake subset benchmark",
    level: "live" as const,
    evidence: `Real held-out subset metrics are generated from the provided archive: ${Math.round(benchmark.metrics.accuracy * 1000) / 10}% accuracy and ${Math.round(benchmark.metrics.eer * 1000) / 10}% EER.`,
    action: "Open Arena and show Real Subset Evaluation."
  }
];

export function JudgeProofView() {
  const scenario = useAegisStore((s) => s.scenario);
  const trustScore = useAegisStore((s) => s.trustScore);
  const honeypotProvider = useAegisStore((s) => s.honeypotProvider);
  const complianceMode = useAegisStore((s) => s.complianceMode);
  const extractedScamData = useAegisStore((s) => s.extractedScamData);
  const auditLog = useAegisStore((s) => s.auditLog);
  const policy = complianceConfigs[complianceMode];

  const liveFacts = [
    { label: "Current trust score", value: `${Math.round(trustScore * 100)}%` },
    { label: "Scenario", value: scenario.replace("_", " ") },
    { label: "Honeypot provider", value: honeypotProvider === "groq" ? "Groq live" : honeypotProvider === "fallback" ? "Fallback labeled" : "Untested" },
    { label: "Compliance", value: `${complianceMode}: recording ${policy.recordingAllowed ? "allowed" : "blocked"}` },
    { label: "Extracted payment", value: extractedScamData.paymentMethod ?? "Pending" },
    { label: "Audit events", value: auditLog.length.toString() }
  ];

  return (
    <motion.section initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mx-auto max-w-7xl px-4 pb-32 pt-24">
      <div className="mb-6 grid gap-5 lg:grid-cols-[0.9fr_1.1fr] lg:items-end">
        <div>
          <div className="text-xs uppercase tracking-[0.24em] text-white/45">Judge Proof Mode</div>
          <h2 className="mt-2 max-w-4xl text-4xl font-semibold tracking-[-0.04em] sm:text-6xl">Proof first. Claims second.</h2>
          <p className="mt-5 max-w-2xl text-lg leading-8 text-white/58">
            This screen is designed for technical judges: what is live, what is heuristic, what is simulated, and what evidence the demo can export.
          </p>
        </div>

        <div className="rounded-xl border border-cyan/20 bg-cyan/10 p-5 backdrop-blur-xl">
          <div className="mb-4 flex items-center gap-2 text-xs uppercase tracking-[0.22em] text-cyan">
            <ShieldCheck className="h-4 w-4" />
            Current Evidence Snapshot
          </div>
          <div className="grid gap-3 sm:grid-cols-2">
            {liveFacts.map((fact) => (
              <div key={fact.label} className="rounded-lg border border-white/10 bg-black/25 p-4">
                <div className="text-xs text-white/45">{fact.label}</div>
                <div className="mt-1 text-lg font-semibold capitalize">{fact.value}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        {proofRows.map((row, index) => (
          <motion.div
            key={row.title}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.05 }}
            className="rounded-xl border border-white/10 bg-white/[0.035] p-5 backdrop-blur-xl"
          >
            <div className="flex items-start justify-between gap-4">
              <div className="flex items-start gap-3">
                <div className="grid h-11 w-11 shrink-0 place-items-center rounded-lg border border-white/10 bg-black/25 text-cyan">
                  {row.title.includes("Guardian") ? <Siren className="h-5 w-5" /> : row.title.includes("Groq") ? <Wifi className="h-5 w-5" /> : row.title.includes("Privacy") ? <LockKeyhole className="h-5 w-5" /> : row.title.includes("Export") ? <Download className="h-5 w-5" /> : row.title.includes("benchmark") ? <TestTube2 className="h-5 w-5" /> : <FileCheck2 className="h-5 w-5" />}
                </div>
                <div>
                  <h3 className="text-lg font-semibold">{row.title}</h3>
                  <p className="mt-2 text-sm leading-6 text-white/58">{row.evidence}</p>
                </div>
              </div>
              <ImplementationBadge level={row.level} />
            </div>
            <div className="mt-4 rounded-lg border border-white/10 bg-black/25 p-3 text-sm text-white/60">
              Demo move: <span className="text-white/85">{row.action}</span>
            </div>
          </motion.div>
        ))}
      </div>

      <div className="mt-5">
        <BenchmarkEvidenceCard />
      </div>

      <div className="mt-5 rounded-xl border border-amber/25 bg-amber/10 p-5 backdrop-blur-xl">
        <div className="flex items-start gap-3">
          <Mic2 className="mt-1 h-5 w-5 shrink-0 text-amber" />
          <div>
            <div className="font-semibold text-amber">Benchmark disclosure for judges</div>
            <p className="mt-2 text-sm leading-6 text-white/65">
              The current Arena visualization still does not run AASIST/RawNet checkpoint inference. The displayed benchmark is a local acoustic-feature baseline on your provided dataset archive with a deterministic held-out split.
            </p>
          </div>
        </div>
      </div>
    </motion.section>
  );
}
